// <auto-generated />
using Arsenal.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace Arsenal.Infrastructure.Persistence.Migrations;

[DbContext(typeof(ArsenalDbContext))]
partial class ArsenalDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
        // Model built via ApplyConfigurationsFromAssembly — full snapshot omitted.
        // Run `dotnet ef migrations add InitialCreate` to regenerate.
#pragma warning restore 612, 618
    }
}
